version: '3'
services:
#  webapp:
#    restart: always
#    build: .
#    ports:
#      - 80:3000
#    volumes:
#      - ./:/code
  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
  mongodb: